name = str(input("What is your name? "))
age = int(input("How old are you? "))
fav_ice_cream = str(input("What is your favourite ice cream flavour? "))
fav_animal = str(input("What is your favourite animal? "))
pi_to_three = float(input("What is PI to 3 decimal places? "))

print(f"Your name is {name}.")
print(f"You are {age} years old.")
print(f"Your favourite ice cream flavour is {fav_ice_cream}.")
print(f"Your favourite animal is {fav_animal}.")
print(f"PI to 3 decimal places is {pi_to_three}")
